import React from "react";


class Table extends React.Component {
    render() {
        return (
            <>
                <h1>Table tag explained...</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Serial Number</th>
                            <th>Name</th>
                            <th>Father's Name</th>
                            <th>Email Id</th>
                            <th>Roll Number</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>01</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>02</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>03</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>01</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>04</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>05</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>06</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>07</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>08</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>09</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>AFSAR</td>
                            <td>KAUSAR</td>
                            <td>afsar.try@gmail.com</td>
                            <td>001</td>
                            <td>
                                <button>Edit</button>
                            </td>
                            <td>
                            <button>Delete</button>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </>
        )
    }
}

export default Table;